// GENERATED FILE - do not edit by hand.
// Regenerate with `npm run typings.api` (scripts/api-typings), which reads the SDK's
// docs/api/massif-api.json - the same schema the C++ property table is built from.

/* eslint-disable */

/**
 * @internal
 * @module
 */

/**
 * The runtime half of the surface API's typings.
 *
 * Only what marshalling needs: each class' OWN properties plus its base, so a dotted path is
 * resolved the way the C++ resolves it - walk the segment, follow the object it names, walk the
 * next. Flattening the closure per class instead would triple this table for nothing.
 *
 * A property is encoded as `name,code` with the code from the table below, plus one argument
 * for the two that need it:
 *
 *   b bool   i int    f float   c color (ARGB int)   s string   v variant (JSON)
 *   t struct (JSON)   p position struct (JSON, convertible between projections)
 *   e enum, followed by the enum's name       o object, followed by the declared class
 *   g bag, followed by the code ONE entry carries - the rest of the path is its key
 */

/** Per class, its own properties (not its bases'), encoded as described above. */
export const PROPS: { [cls: string]: string } = {
    'massif::Address': 'categories,t;country,s;county,s;houseNumber,s;locality,s;name,s;neighbourhood,s;postcode,s;region,s;street,s',
    'massif::AnimationStyle': 'fadeAnimationType,e,AnimationType;phaseInDuration,f;phaseOutDuration,f;relativeSpeed,f;sizeAnimationType,e,AnimationType',
    'massif::AnimationStyleBuilder': 'fadeAnimationType,e,AnimationType;phaseInDuration,f;phaseOutDuration,f;relativeSpeed,f;sizeAnimationType,e,AnimationType',
    'massif::AssetPackage': 'assetNames,t',
    'massif::BalloonPopup': 'balloonPopupEventListener,o,massif::BalloonPopupEventListener;description,s;style,o,massif::BalloonPopupStyle;title,s',
    'massif::BalloonPopupButton': 'style,o,massif::BalloonPopupButtonStyle;tag,v;text,s',
    'massif::BalloonPopupButtonClickInfo': 'button,o,massif::BalloonPopupButton;clickInfo,t;clickType,e,ClickType;vectorElement,o,massif::VectorElement',
    'massif::BalloonPopupButtonStyle': 'backgroundColor,c;buttonWidth,i;cornerRadius,i;strokeColor,c;strokeWidth,i;textColor,c;textFontName,s;textFontSize,i;textMargins,t',
    'massif::BalloonPopupButtonStyleBuilder': 'buttonWidth,i;cornerRadius,i;strokeColor,c;strokeWidth,i;textColor,c;textFontName,s;textFontSize,i;textMargins,t',
    'massif::BalloonPopupMargins': 'bottom,i;left,i;right,i;top,i',
    'massif::BalloonPopupStyle': 'backgroundColor,c;buttonMargins,t;cornerRadius,i;descriptionColor,c;descriptionField,s;descriptionFontName,s;descriptionFontSize,i;descriptionMargins,t;descriptionWrap,b;leftColor,c;leftImage,o,massif::Bitmap;leftMargins,t;rightColor,c;rightImage,o,massif::Bitmap;rightMargins,t;strokeColor,c;strokeWidth,i;titleColor,c;titleField,s;titleFontName,s;titleFontSize,i;titleMargins,t;titleWrap,b;triangleHeight,i;triangleWidth,i',
    'massif::BalloonPopupStyleBuilder': 'buttonMargins,t;cornerRadius,i;descriptionColor,c;descriptionField,s;descriptionFontName,s;descriptionFontSize,i;descriptionMargins,t;descriptionWrap,b;leftColor,c;leftImage,o,massif::Bitmap;leftMargins,t;rightColor,c;rightImage,o,massif::Bitmap;rightMargins,t;strokeColor,c;strokeWidth,i;titleColor,c;titleField,s;titleFontName,s;titleFontSize,i;titleMargins,t;titleWrap,b;triangleHeight,i;triangleWidth,i',
    'massif::BaseMapView': 'cameraPos,p;flightActive,b;flightProgress,f;focusPos,p;mapRenderer,o,massif::MapRenderer;rotation,f;tilt,f;zoom,f',
    'massif::Billboard': 'baseBillboard,o,massif::Billboard;bounds,p;geometry,o,massif::Geometry;rootGeometry,o,massif::Geometry;rotation,f',
    'massif::BillboardStyle': 'animationStyle,o,massif::AnimationStyle;attachAnchorPointX,f;attachAnchorPointY,f;causesOverlap,b;hideIfOverlapped,b;horizontalOffset,f;placementPriority,i;scaleWithDPI,b;verticalOffset,f',
    'massif::BillboardStyleBuilder': 'animationStyle,o,massif::AnimationStyle;attachAnchorPointX,f;attachAnchorPointY,f;causesOverlap,b;hideIfOverlapped,b;horizontalOffset,f;placementPriority,i;scaleWithDPI,b;verticalOffset,f',
    'massif::BinaryData': 'size,i',
    'massif::Bitmap': 'bytesPerPixel,i;colorFormat,e,ColorFormat;height,i;width,i',
    'massif::BundleAssetPackage': 'basePath,s;localAssetNames,t',
    'massif::CacheTileDataSource': 'capacity,i;dataSource,o,massif::TileDataSource',
    'massif::CartoCSSStyleSet': 'assetPackage,o,massif::AssetPackage;cartoCSS,s',
    'massif::CelestialArc': 'belowHorizonVisible,b;clickRadius,f;radius,f;segmented,b;width,f',
    'massif::CelestialLabel': 'anchorPointX,f;anchorPointY,f;backgroundColor,c;backgroundRadius,f;clickable,b;fontName,s;fontSize,f;haloColor,c;haloWidth,f;offsetX,f;offsetY,f;paddingX,f;paddingY,f;text,s;textColor,c',
    'massif::CelestialLayer': 'celestialEventListener,o,massif::CelestialEventListener',
    'massif::CelestialObject': 'altitude,f;azimuth,f;color,c;directionAnchored,b;distance,f;occludedByMap,b;position,p;positionAltitude,f;visible,b',
    'massif::CelestialSprite': 'angularSize,f;bitmap,o,massif::Bitmap;clickRadius,f;screenSize,f;softness,f',
    'massif::ClickInfo': 'clickType,e,ClickType;duration,f',
    'massif::ClusteredVectorLayer': 'animatedClusters,b;clusterElementBuilder,o,massif::ClusterElementBuilder;maximumClusterZoom,f;minimumClusterDistance,f',
    'massif::Color': 'ARGB,i;a,i;b,i;g,i;r,i',
    'massif::CompiledStyleSet': 'assetPackage,o,massif::AssetPackage;styleAssetName,s;styleName,s',
    'massif::ContourTileDataSource': 'baseInterval,f;labelInterval,f;labelStubsEnabled,b;layerName,s;minVisibleZoom,i;resolution,i;seamlessEdgesEnabled,b;simplifyTolerance,f;terrainOptions,o,massif::TerrainOptions',
    'massif::CullState': 'viewState,t',
    'massif::CustomPopup': 'popupHandler,o,massif::CustomPopupHandler',
    'massif::CustomRasterTileLayer': 'shaderSource,s',
    'massif::DirAssetPackage': 'dirPath,s;localAssetNames,t',
    'massif::EditableVectorLayer': 'selectedVectorElement,o,massif::VectorElement;vectorEditEventListener,o,massif::VectorEditEventListener',
    'massif::Feature': 'geometry,o,massif::Geometry;geometryGeoJSON,s;properties,v',
    'massif::FeatureBuilder': 'geometry,o,massif::Geometry',
    'massif::FeatureCollection': 'featureCount,i',
    'massif::FeatureCollectionSearchService': 'featureCollection,o,massif::FeatureCollection;maxResults,i;projection,o,massif::Projection',
    'massif::FogOptions': 'color,c;enabled,b;highColor,c;horizonBlend,f;rangeEnd,f;rangeStart,f;shaderSource,s;spaceColor,c;starIntensity,f;verticalRangeEnd,f;verticalRangeStart,f',
    'massif::GeoJSONGeometryReader': 'targetProjection,o,massif::Projection',
    'massif::GeoJSONGeometryWriter': 'sourceProjection,o,massif::Projection;z,b',
    'massif::GeoJSONVectorTileDataSource': 'defaultLayerBuffer,f;simplifyTolerance,f',
    'massif::GeocodingRequest': 'location,p;locationRadius,f;projection,o,massif::Projection;query,s',
    'massif::GeocodingResult': 'address,t;featureCollection,o,massif::FeatureCollection;projection,o,massif::Projection;rank,f',
    'massif::GeocodingService': 'autocomplete,b;language,s;maxResults,i',
    'massif::Geometry': 'bounds,p;centerPos,p;geoJSON,s;type,e,GeometryType',
    'massif::GeometryCollection': 'geometry,o,massif::MultiGeometry;style,o,massif::GeometryCollectionStyle',
    'massif::GeometryCollectionStyle': 'lineStyle,o,massif::LineStyle;pointStyle,o,massif::PointStyle;polygonStyle,o,massif::PolygonStyle',
    'massif::GeometryCollectionStyleBuilder': 'lineStyle,o,massif::LineStyle;pointStyle,o,massif::PointStyle;polygonStyle,o,massif::PolygonStyle',
    'massif::HTTPTileDataSource': 'HTTPHeaders,g,s;TMSScheme,b;baseURL,s;maxAgeHeaderCheck,b;subdomains,t;timeout,i',
    'massif::HillshadeRasterTileLayer': 'accentColor,c;contourColor,c;contourEnabled,b;contourInterval,f;contourWidth,f;contrast,f;elevationEncodingEnabled,b;exagerateHeightScaleEnabled,b;exaggeration,f;heightScale,f;highlightColor,c;hillshadeMethod,e,HillshadeMethod;illuminationDirection,t;illuminationMapRotationEnabled,b;legacyHeightScaleEnabled,b;normalMapLightingShader,s;shadowColor,c;terrainPaintEnabled,b;terrainPaintFullDetailEnabled,b',
    'massif::Label': 'style,o,massif::LabelStyle',
    'massif::LabelStyle': 'anchorPointX,f;anchorPointY,f;flippable,b;orientationMode,e,BillboardOrientation;renderScale,f;scalingMode,e,BillboardScaling',
    'massif::LabelStyleBuilder': 'anchorPointX,f;anchorPointY,f;flippable,b;orientationMode,e,BillboardOrientation;renderScale,f;scalingMode,e,BillboardScaling',
    'massif::Layer': 'cullDelay,i;metaData,g,v;opacity,f;postProcessed,b;updatePriority,i;visible,b;visibleZoomRange,t',
    'massif::Layers': 'count,i',
    'massif::LightOptions': 'ambientColor,c;ambientIntensity,f;dayCycleLightStops,t;dayCycleLightsEnabled,b;dayCycleRisingLightStops,t;shadowBias,f;shadowCascades,i;shadowCasterMargin,i;shadowDistance,f;shadowMapSize,i;shadowNormalOffset,f;shadowSoftness,f;shadowStrength,f;sunAltitude,f;sunAzimuth,f;sunColor,c;sunIntensity,f;sunOverridingStyle,b;terrainLightingEnabled,b',
    'massif::LightStop': 'ambientColor,c;ambientIntensity,f;sunAltitude,f;sunColor,c;sunIntensity,f',
    'massif::Line': 'geometry,o,massif::LineGeometry;style,o,massif::LineStyle',
    'massif::LineGeometry': 'poses,t',
    'massif::LineStyle': 'bitmap,o,massif::Bitmap;clickWidth,f;lineEndType,e,LineEndType;lineJoinType,e,LineJoinType;stretchFactor,f;width,f',
    'massif::LineStyleBuilder': 'bitmap,o,massif::Bitmap;clickWidth,f;lineEndType,e,LineEndType;lineJoinType,e,LineJoinType;stretchFactor,f;width,f',
    'massif::LocalVectorDataSource': 'geometrySimplifier,o,massif::GeometrySimplifier',
    'massif::Log': 'logEventListener,o,massif::LogEventListener;showDebug,b;showError,b;showInfo,b;showWarn,b;tag,s',
    'massif::MBVectorTileDecoder': 'cartoCSSStyle,o,massif::CartoCSSStyleSet;compiledStyle,o,massif::CompiledStyleSet;featureIdOverride,b;params,g,s;styleLayerNames,t;styleParameters,t;tileFormat,e,TileFormat',
    'massif::ManeuverArrowBuilder': 'lengthAfter,f;lengthBefore,f',
    'massif::MapBounds': 'center,p;delta,t;max,p;min,p',
    'massif::MapBoxOnlineGeocodingService': 'customServiceURL,s',
    'massif::MapBoxOnlineReverseGeocodingService': 'customServiceURL,s',
    'massif::MapClickInfo': 'clickInfo,t;clickPos,p;clickType,e,ClickType',
    'massif::MapEnvelope': 'bounds,p;convexHull,t',
    'massif::MapInteractionInfo': 'animationStarted,b;panAction,b;rotateAction,b;tiltAction,b;zoomAction,b',
    'massif::MapMoveInfo': 'reason,e,MapMoveReason',
    'massif::MapPos': 'x,f;y,f;z,f',
    'massif::MapRange': 'length,f;max,f;midrange,f;min,f',
    'massif::MapRenderer': 'mapRendererListener,o,massif::MapRendererListener;postProcessEffect,o,massif::PostProcessEffect',
    'massif::MapTile': 'frameNr,i;tileId,i;x,i;y,i;zoom,i',
    'massif::MapTilerOnlineTileDataSource': 'customServiceURL,s;timeout,i',
    'massif::MapVec': 'length,f;normalized,t;x,f;y,f;z,f',
    'massif::Marker': 'style,o,massif::MarkerStyle',
    'massif::MarkerStyle': 'anchorPointX,f;anchorPointY,f;bitmap,o,massif::Bitmap;clickSize,f;orientationMode,e,BillboardOrientation;scalingMode,e,BillboardScaling;size,f',
    'massif::MarkerStyleBuilder': 'anchorPointX,f;anchorPointY,f;bitmap,o,massif::Bitmap;clickSize,f;orientationMode,e,BillboardOrientation;scalingMode,e,BillboardScaling;size,f',
    'massif::MultiGeometry': 'geometryCount,i',
    'massif::NMLModel': 'rotationAngle,f;rotationAxis,t;scale,f;style,o,massif::NMLModelStyle',
    'massif::NMLModelStyle': 'modelAsset,o,massif::BinaryData;orientationMode,e,BillboardOrientation;scalingMode,e,BillboardScaling',
    'massif::NMLModelStyleBuilder': 'modelAsset,o,massif::BinaryData;orientationMode,e,BillboardOrientation;scalingMode,e,BillboardScaling',
    'massif::Options': 'DPI,f;ambientLightColor,c;backgroundBitmap,o,massif::Bitmap;baseProjection,o,massif::Projection;clearColor,c;clickMovingTolerance,f;clickTypeDetection,b;debugTileBorders,b;doubleClickDetection,b;doubleClickMaxDuration,f;drawDistance,f;envelopeThreadPoolSize,i;fieldOfViewY,f;focusPointOffset,t;fogOptions,o,massif::FogOptions;freeRoamLookSensitivity,f;freeRoamMode,e,FreeRoamMode;freeRoamMoveSpeed,f;kineticPan,b;kineticRotation,b;kineticZoom,b;labelPadding,f;labelViewDistance,f;layersLabelsProcessedInReverseOrder,b;lightOptions,o,massif::LightOptions;longClickDuration,f;mainLightColor,c;mainLightDirection,t;panBounds,p;panningMode,e,PanningMode;panningSpeedMode,e,PanningSpeedMode;pivotMode,e,PivotMode;renderProjectionMode,e,RenderProjectionMode;restrictedPanning,b;rotatable,b;rotationGestures,b;seamlessPanning,b;skyColor,c;skyOptions,o,massif::SkyOptions;terrainOptions,o,massif::TerrainOptions;tileDrawSize,i;tileLODFactor,f;tileLODMaxZoomLevelsOnScreen,f;tileLODTileCountRatio,f;tileStyleZoomLift,i;tileThreadPoolSize,i;tiltGestureReversed,b;tiltRange,t;userInput,b;zoomGestures,b;zoomOffset,f;zoomRange,t',
    'massif::PackageInfo': 'metaInfo,o,massif::PackageMetaInfo;name,s;packageId,s;packageType,e,PackageType;size,i;tileMask,o,massif::PackageTileMask;version,i',
    'massif::PackageManager': 'localPackages,t;packageManagerListener,o,massif::PackageManagerListener;serverPackageListAge,i;serverPackageListMetaInfo,o,massif::PackageMetaInfo;serverPackages,t',
    'massif::PackageManagerTileDataSource': 'packageManager,o,massif::PackageManager',
    'massif::PackageMetaInfo': 'variant,v',
    'massif::PackageStatus': 'currentAction,e,PackageAction;paused,b;progress,f',
    'massif::PackageTileMask': 'maxZoomLevel,i;stringValue,s',
    'massif::PeliasOnlineGeocodingService': 'customServiceURL,s',
    'massif::PeliasOnlineReverseGeocodingService': 'customServiceURL,s',
    'massif::PersistentCacheTileDataSource': 'cacheOnlyMode,b;open,b',
    'massif::Point': 'geometry,o,massif::PointGeometry;style,o,massif::PointStyle',
    'massif::PointDetailTileDataSource': 'detailZoom,i;layerName,s;maxDetailLevels,i;maxFeatures,i;rankProperty,s',
    'massif::PointGeometry': 'pos,p',
    'massif::PointStyle': 'bitmap,o,massif::Bitmap;clickSize,f;size,f',
    'massif::PointStyleBuilder': 'bitmap,o,massif::Bitmap;clickSize,f;size,f',
    'massif::Polygon': 'geometry,o,massif::PolygonGeometry;style,o,massif::PolygonStyle',
    'massif::Polygon3D': 'geometry,o,massif::PolygonGeometry;height,f;style,o,massif::Polygon3DStyle',
    'massif::Polygon3DStyle': 'sideColor,c',
    'massif::Polygon3DStyleBuilder': 'sideColor,c',
    'massif::PolygonGeometry': 'holes,t;poses,t;rings,t',
    'massif::PolygonStyle': 'lineStyle,o,massif::LineStyle',
    'massif::PolygonStyleBuilder': 'lineStyle,o,massif::LineStyle',
    'massif::Popup': 'anchorPointX,f;anchorPointY,f;style,o,massif::PopupStyle',
    'massif::PopupClickInfo': 'clickInfo,t;clickPos,p;clickType,e,ClickType;elementClickPos,t;popup,o,massif::Popup',
    'massif::PopupDrawInfo': 'DPToPX,f;anchorScreenPos,t;popup,o,massif::Popup;screenBounds,t',
    'massif::PostProcessEffect': 'fragmentShader,s;name,s;terrainDepthRequired,b;terrainNormalsRequired,b',
    'massif::Projection': 'bounds,p;name,s',
    'massif::RasterTileClickInfo': 'clickInfo,t;clickPos,p;clickType,e,ClickType;interpolatedColor,c;layer,o,massif::Layer;mapTile,t;nearestColor,c',
    'massif::RasterTileLayer': 'rasterTileEventListener,o,massif::RasterTileEventListener;textureCacheCapacity,i;tileBlendingSpeed,f;tileFilterMode,e,RasterTileFilterMode',
    'massif::ReverseGeocodingRequest': 'location,p;projection,o,massif::Projection;searchRadius,f',
    'massif::ReverseGeocodingService': 'language,s',
    'massif::RouteMatchingPoint': 'edgeIndex,i;pos,p;type,e,RouteMatchingPointType',
    'massif::RouteMatchingRequest': 'accuracy,f;points,t;projection,o,massif::Projection',
    'massif::RouteMatchingResult': 'matchingEdges,t;matchingPoints,t;points,t;projection,o,massif::Projection;rawResult,s',
    'massif::RoutingInstruction': 'action,e,RoutingAction;azimuth,f;distance,f;geometryTag,v;instruction,s;pointIndex,i;streetName,s;time,f;turnAngle,f',
    'massif::RoutingRequest': 'params,g,v;points,t;projection,o,massif::Projection',
    'massif::RoutingResult': 'instructionCount,i;instructions,t;instructionsJSON,s;pointCount,i;points,t;projection,o,massif::Projection;rawResult,s;totalDistance,f;totalTime,f',
    'massif::RoutingService': 'profile,s',
    'massif::ScreenBounds': 'center,t;max,t;min,t',
    'massif::ScreenPos': 'x,f;y,f',
    'massif::SearchRequest': 'filterExpression,s;geometry,o,massif::Geometry;projection,o,massif::Projection;regexFilter,s;searchRadius,f',
    'massif::SkyOptions': 'atmosphereColor,c;atmosphereLuminance,f;atmosphereSunIntensity,f;enabled,b;groundColor,c;haloColor,c;horizonBlend,f;horizonColor,c;quality,e,SkyQuality;shaderSource,s;skyColor,c;sunDiscEnabled,b;type,e,SkyType',
    'massif::SolidLayer': 'bitmap,o,massif::Bitmap;bitmapScale,f;color,c',
    'massif::Style': 'color,c',
    'massif::StyleBuilder': 'color,c',
    'massif::TerrainOptions': 'autoFlattenDuration,f;autoFlattenParallax,f;autoFlattenRiseDuration,f;autoFlattenTilt,f;backgroundColor,c;billboardOcclusionEnabled,b;billboardOcclusionTolerance,f;bridges3DEnabled,b;cameraClampDuration,f;cameraClearance,f;cameraClearanceFraction,f;depthBias,f;drapeCacheSize,i;drapeFillsEnabled,b;drapeLinesEnabled,b;drapeResolution,i;drapeWorkingSet,i;elevationCacheSize,i;elevationPrefetchEnabled,b;enabled,b;exaggeration,f;flattenMode,e,TerrainFlattenMode;flattenRatio,f;flattened,b;focusLift,f;maxTileZoomCoarsening,i;maxTileZoomOffset,i;maxZoom,i;meshCacheSize,i;meshResolution,i;minZoom,i;noDrapeLayerFilter,s;normalSampleDistance,f;postProcessDownscale,i;seamlessTileEdgesEnabled,b;sharedGroundEnabled,b;subdivideDistance,f;surfaceNodeResolution,i;surfaceShaderSource,s;switching,b;textOcclusionOpacity,f;tileEdgeStitchingEnabled,b;viewDistance,f;viewDistanceFactor,f;viewDistanceMax,f',
    'massif::Text': 'style,o,massif::TextStyle;title,s',
    'massif::TextMargins': 'bottom,i;left,i;right,i;top,i',
    'massif::TextStyle': 'backgroundColor,c;borderColor,c;borderWidth,f;breakLines,b;fontColor,c;fontName,s;fontSize,f;strokeColor,c;strokeWidth,f;textField,s;textMargins,t',
    'massif::TextStyleBuilder': 'backgroundColor,c;borderColor,c;borderWidth,f;breakLines,b;fontName,s;fontSize,f;strokeColor,c;strokeWidth,f;textField,s;textMargins,t',
    'massif::TileData': 'data,o,massif::BinaryData;height,i;maxAge,i;rawPixels,b;replaceWithParent,b;width,i',
    'massif::TileDataSource': 'dataExtent,p;maxOverzoomLevel,i;maxZoom,i;metaData,g,v;minZoom,i;projection,o,massif::Projection',
    'massif::TileDownloadInfo': 'progress,f;tile,t;tileCount,i',
    'massif::TileLayer': 'UTFGridDataSource,o,massif::TileDataSource;UTFGridEventListener,o,massif::UTFGridEventListener;dataSource,o,massif::TileDataSource;frameNr,i;maxOverzoomLevel,i;maxUnderzoomLevel,i;preloading,b;preloadingTileCount,i;projection,o,massif::Projection;synchronizedRefresh,b;tileLoadListener,o,massif::TileLoadListener;tileSubstitutionPolicy,e,TileSubstitutionPolicy;visibleTileCount,i;zoomLevelBias,f',
    'massif::TomTomOnlineGeocodingService': 'customServiceURL,s',
    'massif::TomTomOnlineReverseGeocodingService': 'customServiceURL,s',
    'massif::TorqueTileDecoder': 'animationDuration,f;frameCount,i;resolution,i;styleSet,o,massif::CartoCSSStyleSet',
    'massif::UTFGridClickInfo': 'clickInfo,t;clickPos,p;clickType,e,ClickType;elementInfo,v;layer,o,massif::Layer',
    'massif::ValhallaOnlineRoutingService': 'HTTPHeaders,g,s;customServiceURL,s;timeout,i',
    'massif::Variant': 'arraySize,i;bool,b;double,f;long,i;objectKeys,t;string,s;type,e,VariantType',
    'massif::VectorData': 'elements,t',
    'massif::VectorDataSource': 'dataExtent,p;projection,o,massif::Projection',
    'massif::VectorElement': 'bounds,p;geometry,o,massif::Geometry;id,i;metaData,g,v;visible,b',
    'massif::VectorElementClickInfo': 'clickInfo,t;clickPos,p;clickType,e,ClickType;elementClickPos,p;layer,o,massif::Layer;vectorElement,o,massif::VectorElement',
    'massif::VectorElementDragInfo': 'mapPos,p;screenPos,t;vectorElement,o,massif::VectorElement;vectorElementDragMode,e,VectorElementDragMode',
    'massif::VectorElementSearchService': 'dataSource,o,massif::VectorDataSource;maxResults,i',
    'massif::VectorLayer': 'ZBuffering,b;dataSource,o,massif::VectorDataSource;vectorElementEventListener,o,massif::VectorElementEventListener',
    'massif::VectorTileClickInfo': 'clickInfo,t;clickPos,p;clickType,e,ClickType;feature,o,massif::VectorTileFeature;featureClickPos,p;featureId,i;featureLayerName,s;featurePos,p;featurePosIndex,i;layer,o,massif::Layer;mapTile,t',
    'massif::VectorTileDecoder': 'maxZoom,i;minZoom,i',
    'massif::VectorTileFeature': 'distance,f;id,i;layerName,s;mapTile,t',
    'massif::VectorTileFeatureBuilder': 'id,i;layerName,s;mapTile,t',
    'massif::VectorTileLayer': 'buildingRenderOrder,e,VectorTileRenderOrder;clickHandlerLayerFilter,s;clickRadius,f;labelBlendingSpeed,f;labelPerspectiveScaling,f;labelRenderOrder,e,VectorTileRenderOrder;layerBlendingSpeed,f;rendererLayerFilter,s;tileCacheCapacity,i;tileDecoder,o,massif::VectorTileDecoder;vectorTileEventListener,o,massif::VectorTileEventListener',
    'massif::VectorTileSearchService': 'dataSource,o,massif::TileDataSource;layers,t;maxResults,i;maxZoom,i;minZoom,i;preventDuplicates,b;projection,o,massif::Projection;sortByDistance,b;tileDecoder,o,massif::VectorTileDecoder',
    'massif::ViewState': 'DPI,f;DPToPX,f;FOVY,i;aspectRatio,f;cameraChanged,b;far,f;height,i;near,f;rotation,f;screenHeight,i;screenWidth,i;tilt,f;unitToDPCoef,f;unitToPXCoef,f;width,i;zoom,f;zoom0Distance,f',
    'massif::WKBGeometryWriter': 'bigEndian,b;z,b',
    'massif::WKTGeometryWriter': 'z,b',
    'massif::ZippedAssetPackage': 'localAssetNames,t',
};

/** Per class, its aliases as `alias=path`. */
export const ALIASES: { [cls: string]: string } = {
    'massif::Options': 'background=backgroundBitmap;fog=fogOptions;light=lightOptions;projection=baseProjection;sky=skyOptions;terrain=terrainOptions',
    'massif::TileLayer': 'source=dataSource',
    'massif::VectorTileLayer': 'style=tileDecoder',
};

/** Each class' base, so a lookup walks the chain the C++ property table walks. */
export const BASES: { [cls: string]: string } = {
    'massif::AssetTileDataSource': 'massif::TileDataSource',
    'massif::BalloonPopup': 'massif::Popup',
    'massif::BalloonPopupButtonStyle': 'massif::Style',
    'massif::BalloonPopupButtonStyleBuilder': 'massif::StyleBuilder',
    'massif::BalloonPopupStyle': 'massif::PopupStyle',
    'massif::BalloonPopupStyleBuilder': 'massif::PopupStyleBuilder',
    'massif::Billboard': 'massif::VectorElement',
    'massif::BillboardStyle': 'massif::Style',
    'massif::BillboardStyleBuilder': 'massif::StyleBuilder',
    'massif::BitmapOverlayRasterTileDataSource': 'massif::TileDataSource',
    'massif::BundleAssetPackage': 'massif::AssetPackage',
    'massif::CacheTileDataSource': 'massif::TileDataSource',
    'massif::CelestialArc': 'massif::CelestialObject',
    'massif::CelestialLabel': 'massif::CelestialObject',
    'massif::CelestialLayer': 'massif::Layer',
    'massif::CelestialSprite': 'massif::CelestialObject',
    'massif::ClusteredVectorLayer': 'massif::VectorLayer',
    'massif::CombinedTileDataSource': 'massif::TileDataSource',
    'massif::CompositeVectorTileLayer': 'massif::VectorTileLayer',
    'massif::ContourTileDataSource': 'massif::TileDataSource',
    'massif::CustomPopup': 'massif::Popup',
    'massif::CustomRasterTileLayer': 'massif::RasterTileLayer',
    'massif::DirAssetPackage': 'massif::AssetPackage',
    'massif::DouglasPeuckerGeometrySimplifier': 'massif::GeometrySimplifier',
    'massif::DownloadTask': 'massif::CancelableTask',
    'massif::EPSG3857': 'massif::Projection',
    'massif::EPSG4326': 'massif::Projection',
    'massif::EditableVectorLayer': 'massif::VectorLayer',
    'massif::FetchTask': 'massif::CancelableTask',
    'massif::FetchTaskBase': 'massif::CancelableTask',
    'massif::GeoJSONVectorTileDataSource': 'massif::TileDataSource',
    'massif::GeocodingAddress': 'massif::Address',
    'massif::GeometryCollection': 'massif::VectorElement',
    'massif::GeometryCollectionStyle': 'massif::Style',
    'massif::GeometryCollectionStyleBuilder': 'massif::StyleBuilder',
    'massif::HTTPTileDataSource': 'massif::TileDataSource',
    'massif::HillshadeRasterTileLayer': 'massif::CustomRasterTileLayer',
    'massif::Label': 'massif::Billboard',
    'massif::LabelStyle': 'massif::BillboardStyle',
    'massif::LabelStyleBuilder': 'massif::BillboardStyleBuilder',
    'massif::Line': 'massif::VectorElement',
    'massif::LineGeometry': 'massif::Geometry',
    'massif::LineStyle': 'massif::Style',
    'massif::LineStyleBuilder': 'massif::StyleBuilder',
    'massif::LocalVectorDataSource': 'massif::VectorDataSource',
    'massif::MBTilesTileDataSource': 'massif::TileDataSource',
    'massif::MBVectorTileDecoder': 'massif::VectorTileDecoder',
    'massif::MapBoxElevationDataDecoder': 'massif::ElevationDecoder',
    'massif::MapBoxOnlineGeocodingService': 'massif::GeocodingService',
    'massif::MapBoxOnlineReverseGeocodingService': 'massif::ReverseGeocodingService',
    'massif::MapTilerOnlineTileDataSource': 'massif::TileDataSource',
    'massif::Marker': 'massif::Billboard',
    'massif::MarkerStyle': 'massif::BillboardStyle',
    'massif::MarkerStyleBuilder': 'massif::BillboardStyleBuilder',
    'massif::MemoryCacheTileDataSource': 'massif::CacheTileDataSource',
    'massif::MergedMBVTTileDataSource': 'massif::TileDataSource',
    'massif::MultiGeometry': 'massif::Geometry',
    'massif::MultiLineGeometry': 'massif::MultiGeometry',
    'massif::MultiOSMOfflineGeocodingService': 'massif::GeocodingService',
    'massif::MultiOSMOfflineReverseGeocodingService': 'massif::ReverseGeocodingService',
    'massif::MultiPointGeometry': 'massif::MultiGeometry',
    'massif::MultiPolygonGeometry': 'massif::MultiGeometry',
    'massif::MultiTileDataSource': 'massif::TileDataSource',
    'massif::MultiValhallaOfflineRoutingService': 'massif::RoutingService',
    'massif::NMLModel': 'massif::Billboard',
    'massif::NMLModelStyle': 'massif::BillboardStyle',
    'massif::NMLModelStyleBuilder': 'massif::BillboardStyleBuilder',
    'massif::OSMOfflineGeocodingService': 'massif::GeocodingService',
    'massif::OSMOfflineReverseGeocodingService': 'massif::ReverseGeocodingService',
    'massif::OSRMOfflineRoutingService': 'massif::RoutingService',
    'massif::OrderedTileDataSource': 'massif::TileDataSource',
    'massif::PMTilesTileDataSource': 'massif::TileDataSource',
    'massif::PackageManagerGeocodingService': 'massif::GeocodingService',
    'massif::PackageManagerReverseGeocodingService': 'massif::ReverseGeocodingService',
    'massif::PackageManagerRoutingService': 'massif::RoutingService',
    'massif::PackageManagerTileDataSource': 'massif::TileDataSource',
    'massif::PackageManagerValhallaRoutingService': 'massif::RoutingService',
    'massif::PeliasOnlineGeocodingService': 'massif::GeocodingService',
    'massif::PeliasOnlineReverseGeocodingService': 'massif::ReverseGeocodingService',
    'massif::PersistentCacheTileDataSource': 'massif::CacheTileDataSource',
    'massif::Point': 'massif::VectorElement',
    'massif::PointDetailTileDataSource': 'massif::TileDataSource',
    'massif::PointGeometry': 'massif::Geometry',
    'massif::PointStyle': 'massif::Style',
    'massif::PointStyleBuilder': 'massif::StyleBuilder',
    'massif::Polygon': 'massif::VectorElement',
    'massif::Polygon3D': 'massif::VectorElement',
    'massif::Polygon3DStyle': 'massif::Style',
    'massif::Polygon3DStyleBuilder': 'massif::StyleBuilder',
    'massif::PolygonGeometry': 'massif::Geometry',
    'massif::PolygonStyle': 'massif::Style',
    'massif::PolygonStyleBuilder': 'massif::StyleBuilder',
    'massif::Popup': 'massif::Billboard',
    'massif::PopupStyle': 'massif::BillboardStyle',
    'massif::PopupStyleBuilder': 'massif::BillboardStyleBuilder',
    'massif::RasterTileLayer': 'massif::TileLayer',
    'massif::SGREOfflineRoutingService': 'massif::RoutingService',
    'massif::SolidLayer': 'massif::Layer',
    'massif::TerrariumElevationDataDecoder': 'massif::ElevationDecoder',
    'massif::Text': 'massif::Label',
    'massif::TextStyle': 'massif::LabelStyle',
    'massif::TextStyleBuilder': 'massif::LabelStyleBuilder',
    'massif::TileLayer': 'massif::Layer',
    'massif::TomTomOnlineGeocodingService': 'massif::GeocodingService',
    'massif::TomTomOnlineReverseGeocodingService': 'massif::ReverseGeocodingService',
    'massif::TorqueTileDecoder': 'massif::VectorTileDecoder',
    'massif::TorqueTileLayer': 'massif::VectorTileLayer',
    'massif::ValhallaOfflineRoutingService': 'massif::RoutingService',
    'massif::ValhallaOnlineRoutingService': 'massif::RoutingService',
    'massif::VectorLayer': 'massif::Layer',
    'massif::VectorTileFeature': 'massif::Feature',
    'massif::VectorTileFeatureBuilder': 'massif::FeatureBuilder',
    'massif::VectorTileFeatureCollection': 'massif::FeatureCollection',
    'massif::VectorTileLayer': 'massif::TileLayer',
    'massif::ZippedAssetPackage': 'massif::AssetPackage',
};

/** Per enum, its constants as `NAME=value` - see enumValue and enumName. */
export const ENUMS: { [enumName: string]: string } = {
    AnimationType: 'ANIMATION_TYPE_NONE=0,ANIMATION_TYPE_STEP=1,ANIMATION_TYPE_LINEAR=2,ANIMATION_TYPE_SMOOTHSTEP=3,ANIMATION_TYPE_SPRING=4',
    BillboardOrientation: 'BILLBOARD_ORIENTATION_FACE_CAMERA=0,BILLBOARD_ORIENTATION_FACE_CAMERA_GROUND=1,BILLBOARD_ORIENTATION_GROUND=2',
    BillboardScaling: 'BILLBOARD_SCALING_WORLD_SIZE=0,BILLBOARD_SCALING_SCREEN_SIZE=1,BILLBOARD_SCALING_CONST_SCREEN_SIZE=2',
    ClickType: 'CLICK_TYPE_SINGLE=0,CLICK_TYPE_LONG=1,CLICK_TYPE_DOUBLE=2,CLICK_TYPE_DUAL=3',
    ClusterBuilderMode: 'CLUSTER_BUILDER_MODE_ELEMENTS=0,CLUSTER_BUILDER_MODE_ELEMENT_COUNT=1',
    ColorFormat: 'COLOR_FORMAT_UNSUPPORTED=0,COLOR_FORMAT_BGRA=1,COLOR_FORMAT_RGBA_4444=2,COLOR_FORMAT_RGB_565=3',
    CompositeSourceType: 'COMPOSITE_SOURCE_TYPE_RASTER=0,COMPOSITE_SOURCE_TYPE_HILLSHADE=1,COMPOSITE_SOURCE_TYPE_VECTOR=2',
    FreeRoamMode: 'FREE_ROAM_MODE_OFF=0,FREE_ROAM_MODE_LOOK=1,FREE_ROAM_MODE_FIRST_PERSON=2',
    GeometryType: 'GEOMETRY_TYPE_POINT=0,GEOMETRY_TYPE_LINE=1,GEOMETRY_TYPE_POLYGON=2,GEOMETRY_TYPE_MULTIPOINT=3,GEOMETRY_TYPE_MULTILINE=4,GEOMETRY_TYPE_MULTIPOLYGON=5,GEOMETRY_TYPE_COLLECTION=6',
    HillshadeMethod: 'STANDARD=0,COMBINED=1,IGOR=2,MULTIDIRECTIONAL=3,BASIC=4',
    LineEndType: 'LINE_END_TYPE_NONE=0,LINE_END_TYPE_SQUARE=1,LINE_END_TYPE_ROUND=2',
    LineJoinType: 'LINE_JOIN_TYPE_NONE=0,LINE_JOIN_TYPE_MITER=1,LINE_JOIN_TYPE_BEVEL=2,LINE_JOIN_TYPE_ROUND=3',
    LocalSpatialIndexType: 'LOCAL_SPATIAL_INDEX_TYPE_NULL=0,LOCAL_SPATIAL_INDEX_TYPE_KDTREE=1',
    MBTilesScheme: 'MBTILES_SCHEME_TMS=0,MBTILES_SCHEME_XYZ=1',
    MapMoveReason: 'MAP_MOVE_REASON_GESTURE=0,MAP_MOVE_REASON_ANIMATION=1,MAP_MOVE_REASON_API=2',
    PackageAction: 'PACKAGE_ACTION_READY=0,PACKAGE_ACTION_WAITING=1,PACKAGE_ACTION_DOWNLOADING=2,PACKAGE_ACTION_COPYING=3,PACKAGE_ACTION_REMOVING=4',
    PackageErrorType: 'PACKAGE_ERROR_TYPE_SYSTEM=0,PACKAGE_ERROR_TYPE_CONNECTION=1,PACKAGE_ERROR_TYPE_DOWNLOAD_LIMIT_EXCEEDED=2,PACKAGE_ERROR_TYPE_PACKAGE_TOO_BIG=3,PACKAGE_ERROR_TYPE_NO_OFFLINE_PLAN=4',
    PackageTileStatus: 'PACKAGE_TILE_STATUS_MISSING=0,PACKAGE_TILE_STATUS_PARTIAL=1,PACKAGE_TILE_STATUS_FULL=2',
    PackageType: 'PACKAGE_TYPE_MAP=0,PACKAGE_TYPE_ROUTING=1,PACKAGE_TYPE_GEOCODING=2,PACKAGE_TYPE_VALHALLA_ROUTING=3',
    PanningMode: 'PANNING_MODE_FREE=0,PANNING_MODE_STICKY=1,PANNING_MODE_STICKY_FINAL=2',
    PanningSpeedMode: 'PANNING_SPEED_MODE_MAP=0,PANNING_SPEED_MODE_ANCHORED=1,PANNING_SPEED_MODE_CONSTANT=2',
    PivotMode: 'PIVOT_MODE_TOUCHPOINT=0,PIVOT_MODE_CENTERPOINT=1',
    RasterTileFilterMode: 'RASTER_TILE_FILTER_MODE_NEAREST=0,RASTER_TILE_FILTER_MODE_BILINEAR=1,RASTER_TILE_FILTER_MODE_BICUBIC=2',
    RenderProjectionMode: 'RENDER_PROJECTION_MODE_PLANAR=0,RENDER_PROJECTION_MODE_SPHERICAL=1',
    RouteMatchingPointType: 'ROUTE_MATCHING_POINT_UNMATCHED=0,ROUTE_MATCHING_POINT_INTERPOLATED=1,ROUTE_MATCHING_POINT_MATCHED=2',
    RoutingAction: 'ROUTING_ACTION_HEAD_ON=0,ROUTING_ACTION_FINISH=1,ROUTING_ACTION_NO_TURN=2,ROUTING_ACTION_GO_STRAIGHT=3,ROUTING_ACTION_TURN_RIGHT=4,ROUTING_ACTION_UTURN=5,ROUTING_ACTION_TURN_LEFT=6,ROUTING_ACTION_REACH_VIA_LOCATION=7,ROUTING_ACTION_ENTER_ROUNDABOUT=8,ROUTING_ACTION_LEAVE_ROUNDABOUT=9,ROUTING_ACTION_STAY_ON_ROUNDABOUT=10,ROUTING_ACTION_START_AT_END_OF_STREET=11,ROUTING_ACTION_ENTER_AGAINST_ALLOWED_DIRECTION=12,ROUTING_ACTION_LEAVE_AGAINST_ALLOWED_DIRECTION=13,ROUTING_ACTION_GO_UP=14,ROUTING_ACTION_GO_DOWN=15,ROUTING_ACTION_WAIT=16,ROUTING_ACTION_ENTER_FERRY=17,ROUTING_ACTION_LEAVE_FERRY=18',
    SkyQuality: 'SKY_QUALITY_LOW=0,SKY_QUALITY_MEDIUM=1,SKY_QUALITY_HIGH=2',
    SkyType: 'SKY_TYPE_GRADIENT=0,SKY_TYPE_ATMOSPHERE=1',
    TerrainFlattenMode: 'TERRAIN_FLATTEN_MODE_RENDER=0,TERRAIN_FLATTEN_MODE_FULL=1',
    TileFormat: 'TILE_FORMAT_AUTO=0,TILE_FORMAT_MVT=1,TILE_FORMAT_MLT=2',
    TileLODProfile: 'TILE_LOD_PROFILE_REFERENCE=0,TILE_LOD_PROFILE_MOBILE=1,TILE_LOD_PROFILE_DESKTOP=2',
    TileSubstitutionPolicy: 'TILE_SUBSTITUTION_POLICY_ALL=0,TILE_SUBSTITUTION_POLICY_VISIBLE=1,TILE_SUBSTITUTION_POLICY_NONE=2',
    VariantType: 'VARIANT_TYPE_NULL=0,VARIANT_TYPE_STRING=1,VARIANT_TYPE_BOOL=2,VARIANT_TYPE_INTEGER=3,VARIANT_TYPE_DOUBLE=4,VARIANT_TYPE_ARRAY=5,VARIANT_TYPE_OBJECT=6',
    VectorElementDragMode: 'VECTOR_ELEMENT_DRAG_MODE_VERTEX=0,VECTOR_ELEMENT_DRAG_MODE_ELEMENT=1',
    VectorElementDragPointStyle: 'VECTOR_ELEMENT_DRAG_POINT_STYLE_NORMAL=0,VECTOR_ELEMENT_DRAG_POINT_STYLE_VIRTUAL=1,VECTOR_ELEMENT_DRAG_POINT_STYLE_SELECTED=2',
    VectorElementDragResult: 'VECTOR_ELEMENT_DRAG_RESULT_IGNORE=0,VECTOR_ELEMENT_DRAG_RESULT_STOP=1,VECTOR_ELEMENT_DRAG_RESULT_MODIFY=2,VECTOR_ELEMENT_DRAG_RESULT_DELETE=3',
    VectorTileRenderOrder: 'VECTOR_TILE_RENDER_ORDER_HIDDEN=-1,VECTOR_TILE_RENDER_ORDER_LAYER=0,VECTOR_TILE_RENDER_ORDER_LAST=1',
    massifChangeType: 'PACKAGES_ADDED=0,PACKAGES_DELETED=1',
    massifCommand: 'NOP=0,DOWNLOAD_PACKAGE_LIST=1,DOWNLOAD_PACKAGE=2,IMPORT_PACKAGE=3,REMOVE_PACKAGE=4,DOWNLOAD_STYLE=5',
    massifPackageChangeType: 'PACKAGES_UPDATED=0,PACKAGES_ADDED=1,PACKAGES_DELETED=2',
};

/** The class `create` registers, per kind and spec type. */
export const SPEC_CLASS: { [kind: string]: { [type: string]: string } } = {
    'assets': { 'bundle': 'massif::BundleAssetPackage', 'dir': 'massif::DirAssetPackage', 'zip': 'massif::ZippedAssetPackage' },
    'celestial': { 'arc': 'massif::CelestialArc', 'label': 'massif::CelestialLabel', 'sprite': 'massif::CelestialSprite' },
    'effect': { 'postprocess': 'massif::PostProcessEffect' },
    'element': { 'balloon': 'massif::BalloonPopup', 'line': 'massif::Line', 'marker': 'massif::Marker', 'point': 'massif::Point', 'polygon': 'massif::Polygon', 'text': 'massif::Text' },
    'elementstyle': { 'balloon': 'massif::BalloonPopupStyle', 'line': 'massif::LineStyle', 'marker': 'massif::MarkerStyle', 'point': 'massif::PointStyle', 'polygon': 'massif::PolygonStyle', 'text': 'massif::TextStyle' },
    'feature': { 'feature': 'massif::Feature' },
    'geocoding': { 'multi-osm-offline': 'massif::MultiOSMOfflineGeocodingService', 'multi-osm-offline-reverse': 'massif::MultiOSMOfflineReverseGeocodingService' },
    'geometry': { 'line': 'massif::LineGeometry', 'point': 'massif::PointGeometry', 'polygon': 'massif::PolygonGeometry' },
    'layer': { 'celestial': 'massif::CelestialLayer', 'composite-vector': 'massif::CompositeVectorTileLayer', 'elements': 'massif::VectorLayer', 'hillshade': 'massif::HillshadeRasterTileLayer', 'raster': 'massif::RasterTileLayer', 'solid': 'massif::SolidLayer', 'vector': 'massif::VectorTileLayer' },
    'options': { 'fog': 'massif::FogOptions', 'light': 'massif::LightOptions', 'sky': 'massif::SkyOptions', 'terrain': 'massif::TerrainOptions' },
    'routing': { 'multi-valhalla-offline': 'massif::MultiValhallaOfflineRoutingService', 'valhalla-offline': 'massif::ValhallaOfflineRoutingService', 'valhalla-online': 'massif::ValhallaOnlineRoutingService' },
    'search': { 'request': 'massif::SearchRequest', 'vectortile': 'massif::VectorTileSearchService' },
    'source': { 'assets': 'massif::AssetTileDataSource', 'combined': 'massif::CombinedTileDataSource', 'contour': 'massif::ContourTileDataSource', 'geojson': 'massif::GeoJSONVectorTileDataSource', 'http': 'massif::HTTPTileDataSource', 'local': 'massif::LocalVectorDataSource', 'maptiler': 'massif::MapTilerOnlineTileDataSource', 'mbtiles': 'massif::MBTilesTileDataSource', 'memory-cache': 'massif::MemoryCacheTileDataSource', 'merged-mbvt': 'massif::MergedMBVTTileDataSource', 'multi': 'massif::MultiTileDataSource', 'ordered': 'massif::OrderedTileDataSource', 'persistent-cache': 'massif::PersistentCacheTileDataSource', 'pmtiles': 'massif::PMTilesTileDataSource', 'point-detail': 'massif::PointDetailTileDataSource' },
    'style': { 'mbvt': 'massif::MBVectorTileDecoder' },
    'styleset': { 'cartocss': 'massif::CartoCSSStyleSet', 'project': 'massif::CompiledStyleSet' },
};

/** The kind that builds each class, base chain included. */
export const KIND_OF_CLASS: { [cls: string]: string } = {
    'massif::AssetPackage': 'assets',
    'massif::AssetTileDataSource': 'source',
    'massif::BalloonPopup': 'element',
    'massif::BalloonPopupStyle': 'elementstyle',
    'massif::BalloonPopupStyleBuilder': 'elementstyle',
    'massif::Billboard': 'element',
    'massif::BillboardStyle': 'elementstyle',
    'massif::BillboardStyleBuilder': 'elementstyle',
    'massif::BinaryData': 'data',
    'massif::Bitmap': 'bitmap',
    'massif::BundleAssetPackage': 'assets',
    'massif::CacheTileDataSource': 'source',
    'massif::CartoCSSStyleSet': 'styleset',
    'massif::CelestialArc': 'celestial',
    'massif::CelestialLabel': 'celestial',
    'massif::CelestialLayer': 'layer',
    'massif::CelestialObject': 'celestial',
    'massif::CelestialSprite': 'celestial',
    'massif::CombinedTileDataSource': 'source',
    'massif::CompiledStyleSet': 'styleset',
    'massif::CompositeVectorTileLayer': 'layer',
    'massif::ContourTileDataSource': 'source',
    'massif::CustomRasterTileLayer': 'layer',
    'massif::DirAssetPackage': 'assets',
    'massif::Feature': 'feature',
    'massif::FogOptions': 'options',
    'massif::GeoJSONVectorTileDataSource': 'source',
    'massif::GeocodingRequest': 'geocoding',
    'massif::GeocodingService': 'geocoding',
    'massif::Geometry': 'geometry',
    'massif::HTTPTileDataSource': 'source',
    'massif::HillshadeRasterTileLayer': 'layer',
    'massif::Label': 'element',
    'massif::LabelStyle': 'elementstyle',
    'massif::LabelStyleBuilder': 'elementstyle',
    'massif::Layer': 'layer',
    'massif::LightOptions': 'options',
    'massif::Line': 'element',
    'massif::LineGeometry': 'geometry',
    'massif::LineStyle': 'elementstyle',
    'massif::LineStyleBuilder': 'elementstyle',
    'massif::LocalVectorDataSource': 'source',
    'massif::MBTilesTileDataSource': 'source',
    'massif::MBVectorTileDecoder': 'style',
    'massif::MapTilerOnlineTileDataSource': 'source',
    'massif::Marker': 'element',
    'massif::MarkerStyle': 'elementstyle',
    'massif::MarkerStyleBuilder': 'elementstyle',
    'massif::MemoryCacheTileDataSource': 'source',
    'massif::MergedMBVTTileDataSource': 'source',
    'massif::MultiOSMOfflineGeocodingService': 'geocoding',
    'massif::MultiOSMOfflineReverseGeocodingService': 'geocoding',
    'massif::MultiTileDataSource': 'source',
    'massif::MultiValhallaOfflineRoutingService': 'routing',
    'massif::OrderedTileDataSource': 'source',
    'massif::PMTilesTileDataSource': 'source',
    'massif::PersistentCacheTileDataSource': 'source',
    'massif::Point': 'element',
    'massif::PointDetailTileDataSource': 'source',
    'massif::PointGeometry': 'geometry',
    'massif::PointStyle': 'elementstyle',
    'massif::PointStyleBuilder': 'elementstyle',
    'massif::Polygon': 'element',
    'massif::PolygonGeometry': 'geometry',
    'massif::PolygonStyle': 'elementstyle',
    'massif::PolygonStyleBuilder': 'elementstyle',
    'massif::Popup': 'element',
    'massif::PopupStyle': 'elementstyle',
    'massif::PopupStyleBuilder': 'elementstyle',
    'massif::PostProcessEffect': 'effect',
    'massif::Projection': 'projection',
    'massif::RasterTileLayer': 'layer',
    'massif::ReverseGeocodingRequest': 'geocoding',
    'massif::ReverseGeocodingService': 'geocoding',
    'massif::RouteMatchingRequest': 'routing',
    'massif::RoutingRequest': 'routing',
    'massif::RoutingService': 'routing',
    'massif::SearchRequest': 'search',
    'massif::SkyOptions': 'options',
    'massif::SolidLayer': 'layer',
    'massif::Style': 'elementstyle',
    'massif::StyleBuilder': 'elementstyle',
    'massif::TerrainOptions': 'options',
    'massif::Text': 'element',
    'massif::TextStyle': 'elementstyle',
    'massif::TextStyleBuilder': 'elementstyle',
    'massif::TileDataSource': 'source',
    'massif::TileLayer': 'layer',
    'massif::ValhallaOfflineRoutingService': 'routing',
    'massif::ValhallaOnlineRoutingService': 'routing',
    'massif::VectorDataSource': 'source',
    'massif::VectorElement': 'element',
    'massif::VectorLayer': 'layer',
    'massif::VectorTileDecoder': 'style',
    'massif::VectorTileLayer': 'layer',
    'massif::VectorTileSearchService': 'search',
    'massif::ZippedAssetPackage': 'assets',
};

/**
 * Per class, its own methods: `name,resultCode` and, for an object result, its class.
 *
 *   v void   b bool   i int   f float   s string   j json   d doubles   o object
 */
export const METHODS: { [cls: string]: string } = {
    'massif::BaseMapView': 'fitBounds,v;flyTo,v;mapToScreen,j;moveCameraTo,v;moveTo,v;screenToMap,j;stopFlight,v',
    'massif::CelestialArc': 'setCircle,v;setDirections,v;setSegments,v',
    'massif::CelestialLabel': 'setAnchorPoint,v;setOffset,v',
    'massif::CelestialLayer': 'add,v;clear,v;remove,b',
    'massif::CelestialObject': 'setDirection,v',
    'massif::CompositeVectorTileLayer': 'addExternalDataSource,v;addVectorDataSource,v;getExternalChildLayer,o,massif::Layer;getExternalDataSourceNames,j;removeExternalDataSource,b;setExternalDataSourceMaxOverzoomLevel,v;setExternalDataSourceZoomLevelBias,v',
    'massif::FeatureCollection': 'getFeature,o,massif::Feature',
    'massif::FeatureCollectionSearchService': 'findFeatures,o,massif::FeatureCollection',
    'massif::GeoJSONVectorTileDataSource': 'addFeature,v;createLayer,i;deleteLayer,v;removeFeature,v;setLayerGeoJSON,v;updateFeature,v',
    'massif::GeocodingService': 'calculateAddresses,j',
    'massif::HillshadeRasterTileLayer': 'getElevation,f;getElevations,d',
    'massif::Layer': 'refresh,v',
    'massif::Layers': 'add,v;clear,v;get,o,massif::Layer;insert,v;remove,b;set,v',
    'massif::LightOptions': 'setSunPositionFromTime,v',
    'massif::LocalVectorDataSource': 'add,v;clear,v;remove,b',
    'massif::MBVectorTileDecoder': 'addFallbackFont,v;getStyleParameter,s;setStyleParameter,b;setStyleParameters,v',
    'massif::MultiOSMOfflineGeocodingService': 'add,v;remove,b',
    'massif::MultiOSMOfflineReverseGeocodingService': 'add,v;remove,b',
    'massif::MultiTileDataSource': 'add,v;remove,b',
    'massif::MultiValhallaOfflineRoutingService': 'add,v;addLocale,v;remove,b;setConfigurationParameter,v',
    'massif::PersistentCacheTileDataSource': 'clear,v;startDownloadArea,v;stopAllDownloads,v',
    'massif::PostProcessEffect': 'setFloatParameter,v',
    'massif::ReverseGeocodingService': 'calculateAddresses,j',
    'massif::RouteMatchingRequest': 'setCustomParameter,v',
    'massif::RoutingRequest': 'setCustomParameter,v',
    'massif::RoutingResult': 'getInstruction,o,massif::RoutingInstruction;getPoints,d',
    'massif::RoutingService': 'calculateRoute,o,massif::RoutingResult;matchRoute,o,massif::RouteMatchingResult',
    'massif::TerrainOptions': 'calculateHorizon,d;setSurfaceParameter,v',
    'massif::TileData': 'getMetaDataElement,j',
    'massif::TileDataSource': 'getMetaDataElement,j;loadTile,o,massif::TileData;setMetaDataElement,v',
    'massif::TileLayer': 'clearTileCaches,v',
    'massif::VectorTileFeatureCollection': 'getFeature,o,massif::VectorTileFeature',
    'massif::VectorTileSearchService': 'findFeatures,o,massif::VectorTileFeatureCollection',
};

/**
 * Per class, its own events: the payload's class ('' when it carries none), and
 * whether the SDK asks the listener if the event was consumed.
 */
export const EVENTS: { [cls: string]: { [event: string]: { payload: string; consume: boolean } } } = {
    'massif::Options': { 'map.clicked': { payload: 'massif::MapClickInfo', consume: false }, 'map.idle': { payload: '', consume: false }, 'map.interaction': { payload: 'massif::MapInteractionInfo', consume: false }, 'map.moved': { payload: 'massif::MapMoveInfo', consume: false }, 'map.stable': { payload: 'massif::MapMoveInfo', consume: false } },
    'massif::PersistentCacheTileDataSource': { 'download.completed': { payload: '', consume: false }, 'download.failed': { payload: 'massif::TileDownloadInfo', consume: false }, 'download.progress': { payload: 'massif::TileDownloadInfo', consume: false }, 'download.started': { payload: 'massif::TileDownloadInfo', consume: false } },
    'massif::VectorLayer': { 'vectorelement.clicked': { payload: 'massif::VectorElementClickInfo', consume: true } },
    'massif::VectorTileLayer': { 'vectortile.clicked': { payload: 'massif::VectorTileClickInfo', consume: true } },
};

/** Every class the tables know, by its Java/ObjC leaf name. */
export const CLASS_NAMES = 'Address,AnimationStyle,AnimationStyleBuilder,AssetPackage,AssetTileDataSource,BalloonPopup,BalloonPopupButton,BalloonPopupButtonClickInfo,BalloonPopupButtonStyle,BalloonPopupButtonStyleBuilder,BalloonPopupEventListener,BalloonPopupMargins,BalloonPopupStyle,BalloonPopupStyleBuilder,BaseMapView,Billboard,BillboardStyle,BillboardStyleBuilder,BinaryData,Bitmap,BitmapOverlayRasterTileDataSource,BundleAssetPackage,CacheTileDataSource,CartoCSSStyleSet,CelestialArc,CelestialEventListener,CelestialLabel,CelestialLayer,CelestialObject,CelestialSprite,ClickInfo,ClusterElementBuilder,ClusterFetchTask,ClusteredVectorLayer,Color,CombinedTileDataSource,CompiledStyleSet,CompositeVectorTileLayer,ContourTileDataSource,CullState,CustomPopup,CustomPopupHandler,CustomRasterTileLayer,DataSourceListener,DirAssetPackage,DouglasPeuckerGeometrySimplifier,DownloadTask,EPSG3857,EPSG4326,EditableVectorLayer,ElevationDecoder,EventListener,Feature,FeatureBuilder,FeatureCollection,FeatureCollectionSearchService,FetchTask,FetchTaskBase,FetchingTasks,FetchingTileTasks,FogOptions,GeoJSONGeometryReader,GeoJSONGeometryWriter,GeoJSONVectorTileDataSource,GeocodingAddress,GeocodingRequest,GeocodingResult,GeocodingService,Geometry,GeometryCollection,GeometryCollectionStyle,GeometryCollectionStyleBuilder,GeometrySimplifier,HTTPTileDataSource,HillshadeRasterTileLayer,Label,LabelStyle,LabelStyleBuilder,Layer,Layers,LightOptions,LightStop,Line,LineGeometry,LineStyle,LineStyleBuilder,LocalVectorDataSource,Log,LogEventListener,MBTilesTileDataSource,MBVectorTileDecoder,ManeuverArrowBuilder,MapBounds,MapBoxElevationDataDecoder,MapBoxOnlineGeocodingService,MapBoxOnlineReverseGeocodingService,MapClickInfo,MapEnvelope,MapEventListener,MapInteractionInfo,MapMoveInfo,MapPos,MapRange,MapRenderer,MapRendererListener,MapTile,MapTilerOnlineTileDataSource,MapVec,Marker,MarkerStyle,MarkerStyleBuilder,MassifApi,MassifInterop,MemoryCacheTileDataSource,MergedMBVTTileDataSource,MultiGeometry,MultiLineGeometry,MultiOSMOfflineGeocodingService,MultiOSMOfflineReverseGeocodingService,MultiPointGeometry,MultiPolygonGeometry,MultiTileDataSource,MultiValhallaOfflineRoutingService,NMLModel,NMLModelStyle,NMLModelStyleBuilder,OSMOfflineGeocodingService,OSMOfflineReverseGeocodingService,OSRMOfflineRoutingService,OnChangeListener,Options,OptionsListener,OrderedTileDataSource,PMTilesTileDataSource,PackageInfo,PackageManager,PackageManagerGeocodingService,PackageManagerListener,PackageManagerReverseGeocodingService,PackageManagerRoutingService,PackageManagerTileDataSource,PackageManagerValhallaRoutingService,PackageMetaInfo,PackageStatus,PackageTileMask,PeliasOnlineGeocodingService,PeliasOnlineReverseGeocodingService,PersistentCacheTileDataSource,PersistentTaskQueue,Point,PointDetailTileDataSource,PointGeometry,PointStyle,PointStyleBuilder,Polygon,Polygon3D,Polygon3DStyle,Polygon3DStyleBuilder,PolygonGeometry,PolygonStyle,PolygonStyleBuilder,Popup,PopupClickInfo,PopupDrawInfo,PopupStyle,PopupStyleBuilder,PostProcessEffect,Projection,RasterTileClickInfo,RasterTileEventListener,RasterTileLayer,RedrawRequestListener,RendererCaptureListener,ReverseGeocodingRequest,ReverseGeocodingService,RouteMatchingEdge,RouteMatchingPoint,RouteMatchingRequest,RouteMatchingResult,RoutingInstruction,RoutingRequest,RoutingResult,RoutingService,SGREOfflineRoutingService,ScreenBounds,ScreenPos,SearchRequest,SkyOptions,SolidLayer,Style,StyleBuilder,TerrainOptions,TerrariumElevationDataDecoder,Text,TextMargins,TextStyle,TextStyleBuilder,TileData,TileDataSource,TileDecoderListener,TileDownloadInfo,TileDownloadListener,TileInfo,TileLayer,TileLoadListener,TileUtils,TomTomOnlineGeocodingService,TomTomOnlineReverseGeocodingService,TorqueTileDecoder,TorqueTileLayer,TouchHandlerListener,UTFGridClickInfo,UTFGridEventListener,UiDispatcher,ValhallaOfflineRoutingService,ValhallaOnlineRoutingService,Variant,VariantArrayBuilder,VariantObjectBuilder,VectorData,VectorDataSource,VectorEditEventListener,VectorElement,VectorElementClickInfo,VectorElementDragInfo,VectorElementEventListener,VectorElementSearchService,VectorLayer,VectorTileClickInfo,VectorTileDecoder,VectorTileEventListener,VectorTileFeature,VectorTileFeatureBuilder,VectorTileFeatureCollection,VectorTileLayer,VectorTileSearchService,ViewState,WKBGeometryReader,WKBGeometryWriter,WKTGeometryReader,WKTGeometryWriter,ZippedAssetPackage';
