import { MapPos } from './core/core';
import { MapPosVector, MapPosVectorVector } from './core/core.android';
import { Projection } from './projections/projection.android';
export declare const nativeProperty: (target: Object, key: string | symbol, converter?: any) => void;
export declare function nativeColorProperty(target: Object, key: string | symbol): void;
export declare function nativeEnumProperty(enumType: any): (target: Object, key: string | symbol) => void;
export declare function nativeCartoImageProperty(target: Object, key: string | symbol): void;
export declare function nativeImageProperty(target: Object, key: string | symbol): void;
export declare function mapPosVectorFromArgs(poses: MapPosVector | MapPos[], projection?: Projection): com.carto.core.MapPosVector;
export declare function mapPosVectorVectorFromArgs(poses: MapPosVectorVector | MapPos[][], projection?: Projection): com.carto.core.MapPosVectorVector;
